---
registry:
  host: "registry.hub.docker.com"

clair:
  host: "172.17.0.1:6060"

output:
  format: json # "json", "table", "short-table" or quiet
# uncomment if you want to use the rocketchat output feature
#  rocketchat:
#    webhook_url: rocket-chat.com/hooks/...
#    receiver: "#general,@admin"

fail_on:
  score: 379
  big_vulnerability: true